### ISSUE TITLE
scope.Snapshot() clears Histogram values

### ISSUE THREAD

**Issue by jkanywhere** [uber-go/tally#141]
### Steps to Reproduce:

Instantiate a testScope.
Emit some metrics.

Call `Snapshot()` multiple times on a `testScope`.

As demonstrated by running existing test in a loop: https://github.com/uber-go/tally/compare/master...jkanywhere:jkline-histogram-snapshot-broken 

### Expected Result

Value of metrics is the same after each call to `Snapshot()` because no new metrics have been emitted.

### Actual Result

The expected result holds for counters, gauges, and times.
But, the value stored in Histograms is cleared after each call to `Snapshot()`.

### Analysis

The value stored in Histograms is cleared after each call to `Snapshot()`. Applies to both Value buckets and Duration buckets.

Am I misunderstanding the intended use of `Snapshot()`? I've been assuming it is safe to call multiple times during the same test.

A histogram is a map of float or duration to `counter`.
`(*histogram).snapshotValues()` and `(*histogram).snapshotDurations()` each call `(*counter).value()` for each bucket.

Calling `(*counter).value()` changes the value stored: https://github.com/uber-go/tally/blob/master/stats.go#L73

Should probably call `(*counter).snapshot()` instead, as is done when snapshotting counters themselves.

**Comment by mway** [comment]
this has been released in [v3.3.17](https://github.com/uber-go/tally/releases/tag/v3.3.17), feel free to update pins as necessary.

thanks for fixing this!
