### ISSUE TITLE
Prometheus reporter conflates summaries and histograms

### ISSUE THREAD

**Issue by akshayjshah** [uber-go/tally#17]
All references to histograms in the Prometheus reporter, examples, and docs are erroneous: we're exporting timers as Summaries, not Histograms. This is confusing, since Prometheus also supports Histograms, which have [different strengths and weaknesses](https://prometheus.io/docs/practices/histograms/). (In particular, summaries can't be accurately aggregated, while histograms can.)

One straightforward option is to just use `summary` or `sketch` instead of `histogram` when naming variables and types.

/cc @byxorna @robskillington

**Comment by robskillington** [comment]
Sure thing.  We can also add the ability to configure whether to use histograms or summaries when creating the Prometheus reporter.

We also need to make Prometheus a `CachedStatsReporter` to avoid unnecessary allocations.

**Comment by robskillington** [comment]
This is fixed with #25 .  Let me know if there are any further asks you have @akshayjshah .
