### ISSUE TITLE
"github.com/uber-go/tally/v4/prometheus".Reporter does not implement "github.com/uber-go/tally/v4".CachedStatsReporter

### ISSUE THREAD

**Issue by liubang** [uber-go/tally#170]
I've got tally using `go get -u github.com/uber-go/tally`, and then run the following test code:

```go
package main

import (
	"fmt"
	"net/http"
	"time"
	tally "github.com/uber-go/tally/v4"
	promreporter "github.com/uber-go/tally/v4/prometheus"
)

func main() {
	r := promreporter.NewReporter(promreporter.Options{})

	scope, closer := tally.NewRootScope(tally.ScopeOptions{
		Prefix:         "my_service",
		Tags:           map[string]string{},
		CachedReporter: r,
		Separator:      promreporter.DefaultSeparator,
	}, 1*time.Second)
	defer closer.Close()

	http.Handle("/metrics", r.HTTPHandler())
	fmt.Printf("Serving :8080/metrics\n")
	fmt.Printf("%v\n", http.ListenAndServe(":8080", nil))
	select {}
}
```

then produce error:

```
cannot use r (type "github.com/uber-go/tally/v4/prometheus".Reporter) as type "github.com/uber-go/tally/v4".CachedStatsReporter in field value:
	"github.com/uber-go/tally/v4/prometheus".Reporter does not implement "github.com/uber-go/tally/v4".CachedStatsReporter (wrong type for AllocateCounter method)
		have AllocateCounter(string, map[string]string) "github.com/uber-go/tally".CachedCount
		want AllocateCounter(string, map[string]string) "github.com/uber-go/tally/v4".CachedCount
```

It is found that $GOPATH/pkg/mod/github.com/uber-go/tally/v4@v4.0.0 is different from the code in the corresponding tag on GitHub. I wonder if you've retagged v4.0.0?

**Comment by liubang** [comment]
@mway

**Comment by mway** [comment]
Yes, we deleted the original v4.0.0 immediately after it was pushed and re-cut it due to not having fixed v4 imports prior.

You shouldn't have issues if you re-pull. Sorry for the inconvenience!

**Comment by liubang** [comment]
You can refer to my steps to try to reproduce this problem. I think the only fix is to tag a new version, and make sure to not move that tag. The problem is similar to [https://github.com/grafeas/grafeas/issues/377](https://github.com/grafeas/grafeas/issues/377)

**Comment by mway** [comment]
Retagged as v4.0.1.
