### ISSUE TITLE
In-memory access to metric values

### ISSUE THREAD

**Issue by akshayjshah** [uber-go/tally#18]
Is there any plan to offer read access to metrics? I'm particularly interested in reading the accumulated value of counters, the current value of gauges, and whatever we can get for timers. This would let us serve simple admin pages directly from the instrumented process.

**Comment by robskillington** [comment]
There is the ability to perform that already for use in tests:
https://github.com/uber-go/tally/blob/master/scope.go#L101

**Comment by robskillington** [comment]
I am reopening this as I believe that this request is different to the title of the issue.

Essentially I believe you are looking for a scrape endpoint.  Tally now has a Prometheus reporter.  The plan moving forward I believe is to add a multi-reporter so you can report into a Prometheus backend and then retrieve the HTTPHandler for the Prometheus backend to offer metrics created by Tally as scrapeable.

**Comment by robskillington** [comment]
Now that the `prometheus` reporter module is first class you can access metric values using the registry you pass in by calling `Gather()` on it.

You can also call `HTTPHandler()` on the reporter exposes to serve simple metrics pages.  

Let me know if this addresses your ask @akshayjshah and if not we can reopen this issue.

As mentioned before you can use a `TestScope` if you want to access the metric values just for tests, no reporter required.
