### ISSUE TITLE
Histogram support

### ISSUE THREAD

**Issue by akshayjshah** [uber-go/tally#19]
Are there any plans to support histograms as a first-class metric type in `tally`? If so, is there a timeline?

**Comment by robskillington** [comment]
There is plans to support histograms, in fact they were added to the interface in a PR that made large API changes and then rolled back until downstream consumers of tally can properly support the histogram API.

**Comment by robskillington** [comment]
@Raynos is looking to add histograms to `tally` soon.

**Comment by Raynos** [comment]
I was looking into it, but then my weekend dissapeared.

Let me release the lock and update this issue when I really start working on it.

**Comment by akshayjshah** [comment]
This landed in the 2.0 release (hooray)!
