### ISSUE TITLE
log spamming

### ISSUE THREAD

**Issue by mschneider82** [uber-go/tally#199]
I updated from 3.5.0 to 3.5.2 and now i get my logs spammed with this message:

2023/01/24 10:10:18 counters: 3, gauges: 34, histograms: 2
2023/01/24 10:10:19 counters: 3, gauges: 34, histograms: 2
2023/01/24 10:10:20 counters: 3, gauges: 34, histograms: 2
2023/01/24 10:10:21 counters: 3, gauges: 34, histograms: 2
2023/01/24 10:10:22 counters: 3, gauges: 34, histograms: 2
2023/01/24 10:10:23 counters: 3, gauges: 34, histograms: 2
2023/01/24 10:10:24 counters: 3, gauges: 34, histograms: 2
2023/01/24 10:10:25 counters: 3, gauges: 34, histograms: 2
2023/01/24 10:10:26 counters: 3, gauges: 34, histograms: 2

It seems that c347bbf48d7998560fa8a821d08ea5b425deda3e introduced a log.Printf line.

**Comment by brawndou** [comment]
hi, the spammy log message has been removed. this and other fixes will be in the next release

**Comment by mschneider82** [comment]
Ok i made two PR to remove it for both branches.

**Comment by brawndou** [comment]
both branches have been updated, will cut a new release once other fixes have also been tested/merged
