### ISSUE TITLE
Roadmap & SemVer

### ISSUE THREAD

**Issue by akshayjshah** [uber-go/tally#20]
What's the current version number for this library (assuming you intend to eventually use semver)? It doesn't appear to have any releases or tags, so I can't tell if it's alpha, beta, stable, or what. If it's not yet stable, is there a milestone or roadmap for 1.0?

**Comment by robskillington** [comment]
Hey Akshay,

This is a very new repository so perhaps we can go ahead and tag it at 0.1.0 for now.  Let me discuss with the contributors and agree on an API we would like to achieve for a 1.0.0 release.

**Comment by akshayjshah** [comment]
Cool. Having some semver tag, even if it's 0.0.1, will help a lot internally. Right now, tally is very prone to version conflicts.

**Comment by robskillington** [comment]
We have a v1.0.0 now:
https://github.com/uber-go/tally/releases/tag/v1.0.0

Roadmap still pending.

**Comment by akshayjshah** [comment]
💯  Awesome - much appreciated.

**Comment by akshayjshah** [comment]
Any updates on the roadmap?

**Comment by robskillington** [comment]
Not really, there's not too much on the roadmap with the exception of a scrape endpoint.  We can add this soon.
