### ISSUE TITLE
Add options to the NewScope APIs

### ISSUE THREAD

**Issue by jeffbean** [uber-go/tally#29]
To interact with `NewCachedRootScope` can we change to having options?

`WithInterval`  seems to fall under optional since it can have sane defaults. 
`WithTags` is also optional in this case as well. 
`WithSeparator` looks to be optional as well but this one I'm not sure how required it is.

**Comment by robskillington** [comment]
Thanks for the issue, this was implemented in v1.2.0 and there is a `ScopeOptions` passed into the `Scope`.
