### ISSUE TITLE
why newrootscope return a struct not interface 

### ISSUE THREAD

**Issue by GrapeBaBa** [uber-go/tally#49]
Currently I am using tally for metrics implementation, i note newrootscope not return Scope interface but subscope return that. Seems scope struct implement snapshot method, it describe this method should use in test.

**Comment by prateek** [comment]
Hey @GrapeBaBa 

`NewRootScope` (the exported method) - [1], does return an interface: 
```
func NewRootScope(opts ScopeOptions, interval time.Duration) (Scope, io.Closer) {
...
}
```

And for tests, you can use `NewTestScope` - [2], which as you noted, gives you the ability to snapshot metrics.
```
// NewTestScope creates a new Scope without a stats reporter with the
// given prefix and adds the ability to take snapshots of metrics emitted
// to it.
func NewTestScope(
	prefix string,
	tags map[string]string,
) TestScope {
...
}

// TestScope is a metrics collector that has no reporting, ensuring that
// all emitted values have a given prefix or set of tags
type TestScope interface {
	Scope

	// Snapshot returns a copy of all values since the last report execution,
	// this is an expensive operation and should only be use for testing purposes
	Snapshot() Snapshot
}
```

Internally, both ctors (`NewTestScope` and `NewRootScope`) rely on the method `newRootScope` which returns a struct. This is an implementation detail that external callers of the library should not rely upon. 

HTH

[1]: https://github.com/uber-go/tally/blob/v3.0.2/scope.go#L108
[2]: https://github.com/uber-go/tally/blob/v3.0.2/scope.go#L116

**Comment by GrapeBaBa** [comment]
@prateek Oh, I confused NewRootScope and newRootScope methods. Thanks your reply.
