### ISSUE TITLE
apache thrift.TProcessorFunction now expects context

### ISSUE THREAD

**Issue by jkanywhere** [uber-go/tally#56]
https://github.com/apache/thrift/commit/5b4c6bfc627ddbd56d1e98d4b818bec8cd8a5efd adds `context.Context` to the `thrift.TProcessorFunction.Process` function,
and `m3ProcessorEmitMetricBatch.Process` function defined at [m3/thrift/m3.go#L154](https://github.com/uber-go/tally/blob/master/m3/thrift/m3.go#L154) does not accept context.
[m3/thrift/m3.go#L137](/uber-go/tally/blob/master/m3/thrift/m3.go#L137) does not pass context.

Similar problems with [uber/tchannel-go/blob/dev/thrift/gen-go/meta/meta.go](https://github.com/uber/tchannel-go/blob/dev/thrift/gen-go/meta/meta.go#L289)

```
# .../vendor/github.com/uber/tchannel-go/thrift/gen-go/meta
vendor/github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:289: cannot use metaProcessorHealth literal (type *metaProcessorHealth) as type thrift.TProcessorFunction in assignment:
	*metaProcessorHealth does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
vendor/github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:290: cannot use metaProcessorThriftIDL literal (type *metaProcessorThriftIDL) as type thrift.TProcessorFunction in assignment:
	*metaProcessorThriftIDL does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
vendor/github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:291: cannot use metaProcessorVersionInfo literal (type *metaProcessorVersionInfo) as type thrift.TProcessorFunction in assignment:
	*metaProcessorVersionInfo does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
vendor/github.com/uber/tchannel-go/thrift/gen-go/meta/meta.go:301: not enough arguments in call to processor.Process
	have (int32, thrift.TProtocol, thrift.TProtocol)
	want (context.Context, int32, thrift.TProtocol, thrift.TProtocol)
# .../vendor/github.com/uber-go/tally/m3/thrift
vendor/github.com/uber-go/tally/m3/thrift/m3.go:127: cannot use m3ProcessorEmitMetricBatch literal (type *m3ProcessorEmitMetricBatch) as type thrift.TProcessorFunction in assignment:
	*m3ProcessorEmitMetricBatch does not implement thrift.TProcessorFunction (wrong type for Process method)
		have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
		want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
vendor/github.com/uber-go/tally/m3/thrift/m3.go:137: not enough arguments in call to processor.Process
	have (int32, thrift.TProtocol, thrift.TProtocol)
	want (context.Context, int32, thrift.TProtocol, thrift.TProtocol)
make: *** [.tmp/faux.test] Error 2
```

**Comment by prateek** [comment]
@jkanywhere `tally` is pinned to an older version of thrift (`0.10.0`), which does not have the patch you referenced. It's not trivial for us to change this - testing compatibility and so on. Can you live with an older version of `thrift`?

**Comment by jkanywhere** [comment]
I'm a little confused by your statement "`tally` is pinned to an older version of thrift (0.10.0)"

Before `glide up` I was using b2a4d4ae21c789b689dd162deb819665567f481c which appears to be the 0.10.0 tag.

`tally` is pinned to https://github.com/apache/thrift/commit/9549b25c77587b29be4e0b5c258221a4ed85d37a , i'm not sure the significance of this commit.

what am I missing?

Either way, I can live with an old version of `thrift` without context.

thanks!

**Comment by prateek** [comment]
@jkanywhere Glad you can work around it.

here's what I mean by that - glide.yaml in tally specifies [9549b25c77587b29be4e0b5c258221a4ed85d37a](https://github.com/uber-go/tally/blob/master/glide.yaml#L15) as the thrift version to use, which is [thrift v0.10.0](https://github.com/apache/thrift/commit/9549b25c77587b29be4e0b5c258221a4ed85d37a). 

glide doesn't pin transitive dependencies correctly. E.g. if your project (or another dependency apart from tally) depends on thrift, and doesn't pin the version, `glide up` will happily update the version of thrift, despite `tally` asking for 0.10.0.

**Comment by prashantv** [comment]
`glide.yaml` should ideally never pin commit hashes, it should pin ranges. Take a look at the `glide.yaml` from some of our other projects:
https://github.com/uber/tchannel-go/blob/dev/glide.yaml#L4
https://github.com/thriftrw/thriftrw-go/blob/dev/glide.yaml

A commit hash forces all consumers of this library to pin to the exact same version, and if there's a mismatch, their `glide up` will fail. This is particularly painful if they use 2 separate libraries which ask for different commit hashes. If we instead do a range, then tally is less likely to cause problems on glide update since it'll accept multiple versions (e.g., `0.9.3` probably works fine with tally, but is not accepted right now).
