### ISSUE TITLE
Update pins for github.com/m3db/prometheus_client_golang

### ISSUE THREAD

**Issue by vdarulis** [uber-go/tally#99]
We should cut a new release of `github.com/m3db/prometheus_client_golang` and pin tally to `^0.8.1`, so someone asking for a semver of the forked client won't pick up changes in the unreleased commits.

Given glide/dep/etc. don't respect restrictions coming from transient deps, a user asking for semver for `github.com/m3db/prometheus_client_golang` will not get the exact commit Tally requires, and will have a broken Prometheus reporter, or just compilation failures. 

Related to issue #82 - this is why we should stop pinning to hashes.

**Comment by robskillington** [comment]
We ended up pinning the remaining dependencies, let's hope this doesn't blow up builds.

**Comment by robskillington** [comment]
We ended up pinning the remaining dependencies, let's hope this doesn't blow up builds.
